dist: xenial # needed to use python 3.7
language: python
branches:
  only:
    - master
python:
  - 3.7
cache:
  directories:
  - node_modules
install:
  - pip install -r ./docsrc/requirements.txt
  - pip install -U pip
  - pip install pipenv
  - pipenv install # set up the environment
  - curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.1.0 # install vale
  - export PATH="./bin:$PATH"
# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
script:
  - skip # Travis requires a `script` property, but we do not need it
stages:
  - build and test
  - deploy
jobs:
  include:
    - stage: build and test # This stage builds and lints in parallel
      name: Build
      script: pipenv run make html # build the docs
      #- script: vale --minAlertLevel error source # run vale
      - script: curl -H "Authorization: token 4b37eda17ae0607db8b6236becf8e4bf65689859" https://api.github.ibm.com
      name: Test
    - stage: deploy
      name: Deploy to GitHub Pages
      if: (NOT type IN (pull_request)) AND (branch = master) # only deploy if merging on master
      script: pipenv run make html
    #- script: curl -H "Authorization: token $token" https://api.github.ibm.com
      deploy:
        provider: pages # deploy on github pages
        skip_cleanup: true
        github_token: 4b37eda17ae0607db8b6236becf8e4bf65689859
        local_dir: build/html
